const questions = {
  friends: [
    { id: 'q1', text: 'What is the name of Ross and Carol’s son?', answers: ['Ben', 'Jack', 'Michael', 'Adam'] },
    { id: 'q2', text: 'Which character famously said, "We were on a break!"?', answers: ['Ross', 'Chandler', 'Joey', 'Monica'] },
    { id: 'q3', text: 'What is the name of the coffee house where the friends often hang out?', answers: ['Central Perk', 'The Coffee Bean', 'Cafe Central', 'Perk & Brew'] },
    { id: 'q4', text: 'Which character had a twin sister named Ursula?', answers: ['Phoebe', 'Rachel', 'Monica', 'Janice'] },
    { id: 'q5', text: 'Who was the last of the six friends to find out about Monica and Chandler’s relationship?', answers: ['Ross', 'Phoebe', 'Joey', 'Rachel'] },
    { id: 'q6', text: 'What is the name of Joey’s stuffed penguin?', answers: ['Hugsy', 'Benny', 'Waddles', 'Penguin Joe'] },
    { id: 'q7', text: 'What job does Chandler do at the beginning of the series?', answers: ['Data processor', 'Advertising executive', 'Transponster', 'Accountant'] },
    { id: 'q8', text: 'What does Rachel’s sister Amy call Emma, Rachel and Ross’s baby?', answers: ['Ella', 'Emily', 'Emmett', 'Esme'] },
    { id: 'q9', text: 'Which friend was famously overweight as a teenager?', answers: ['Monica', 'Chandler', 'Joey', 'Rachel'] },
    { id: 'q10', text: 'What was the name of Ross’s second wife?', answers: ['Emily', 'Rachel', 'Carol', 'Susan'] },
    { id: 'q11', text: 'What was the name of the coffee shop where Rachel worked after she left Central Perk?', answers: ['Ralph Lauren', 'Stryker’s', 'Central Perk', 'Gunther’s Café'] },
    { id: 'q12', text: 'What is Joey’s favorite food?', answers: ['Pizza', 'Sandwiches', 'Burgers', 'Pasta'] },
    { id: 'q13', text: 'What is the name of Ross and Monica’s dog?', answers: ['Chi-Chi', 'Amy', 'Coco', 'Rita'] },
    { id: 'q14', text: 'Which character was a paleontologist?', answers: ['Ross', 'Chandler', 'Joey', 'Phoebe'] },
    { id: 'q15', text: 'What is the name of Phoebe’s song about a cat?', answers: ['Smelly Cat', 'Fluffy Cat', 'Wicked Cat', 'Crazy Cat'] },
    { id: 'q16', text: 'Which character worked at the coffee shop Central Perk?', answers: ['Rachel', 'Phoebe', 'Monica', 'Janice'] },
    { id: 'q17', text: 'What is the name of Monica’s restaurant?', answers: ['Alessandro’s', 'Mamma Mia', 'Central Perk', 'Ralph Lauren'] },
    { id: 'q18', text: 'Which character famously danced in the “Routine” at the school dance?', answers: ['Ross and Monica', 'Joey and Rachel', 'Chandler and Phoebe', 'Rachel and Monica'] },
    { id: 'q19', text: 'Who gets trapped in an ATM vestibule with a supermodel?', answers: ['Chandler', 'Joey', 'Ross', 'Monica'] },
    { id: 'q20', text: 'What is the name of maternal grandmother of Ross and Monica Geller?', answers: ['Althea', 'Emmet', 'Sandra', 'Emily'] },
  ],

  brooklynNineNine: [
    { id: 'q1', text: 'What is the name of Jake Peralta’s partner?', answers: ['Amy Santiago', 'Rosa Diaz', 'Terry Jeffords', 'Gina Linetti'] },
    { id: 'q2', text: 'Who is the captain of the 99th precinct?', answers: ['Ray Holt', 'Rosa Diaz', 'Jake Peralta', 'Amy Santiago'] },
    { id: 'q3', text: 'What is Terry Jeffords’ favorite snack?', answers: ['Yogurt', 'Cookies', 'Chips', 'Pretzels'] },
    { id: 'q4', text: 'What is Gina Linetti known for?', answers: ['Her eccentric personality', 'Her baking skills', 'Her singing', 'Her detective work'] },
    { id: 'q5', text: 'What is the name of Jake Peralta’s nemesis?', answers: ['Detective Daniels', 'Detective Hawkins', 'Detective Peralta', 'Detective Boyle'] },
    { id: 'q6', text: 'Which precinct does the show revolve around?', answers: ['99th', '22nd', '55th', '77th'] },
    { id: 'q7', text: 'What is Captain Holt’s husband’s name?', answers: ['Kevin Cozner', 'Jake Peralta', 'Terry Jeffords', 'Charles Boyle'] },
    { id: 'q8', text: 'What is Rosa Diaz’s favorite type of music?', answers: ['Heavy metal', 'Jazz', 'Classical', 'Pop'] },
    { id: 'q9', text: 'Which character often says “Cool, cool, cool, cool, cool, cool, cool, cool, cool, cool, cool.”?', answers: ['Jake Peralta', 'Terry Jeffords', 'Charles Boyle', 'Gina Linetti'] },
    { id: 'q10', text: 'What is Captain Holt’s favorite hobby?', answers: ['Star Trek', 'Cooking', 'Golf', 'Reading'] },
    { id: 'q11', text: 'What is the name of Jake Peralta’s favorite action movie series?', answers: ['Die Hard', 'Lethal Weapon', 'Bad Boys', 'The Fast and the Furious'] },
    { id: 'q12', text: 'What is Amy Santiago’s biggest goal?', answers: ['To become a captain', 'To open a bakery', 'To travel the world', 'To become a detective'] },
    { id: 'q13', text: 'What does Terry Jeffords name his children?', answers: ['Caitlyn and Jack', 'Josh and Daisy', 'Michael and Katie', 'Erica and Finn'] },
    { id: 'q14', text: 'What is Rosa Diaz’s favorite way to unwind?', answers: ['Motorcycling', 'Yoga', 'Cooking', 'Painting'] },
    { id: 'q15', text: 'What is the name of the precinct’s break room table?', answers: ['The Table of Lies', 'The Potato Table', 'The Breakfast Table', 'The Cop Table'] },
    { id: 'q16', text: 'What is Charles Boyle’s favorite food?', answers: ['Chicken', 'Pizza', 'Hot dogs', 'Salad'] },
    { id: 'q17', text: 'What is Gina Linetti’s job title?', answers: ['Civilian administrator', 'Detective', 'Captain', 'Forensic expert'] },
    { id: 'q18', text: 'What is Jake Peralta’s favorite holiday?', answers: ['Christmas', 'Halloween', 'Thanksgiving', 'New Year’s'] },
    { id: 'q19', text: 'What is Captain Holt’s dog’s name?', answers: ['Cheddar', 'Rex', 'Rover', 'Max'] },
    { id: 'q20', text: 'What is the name of Jake and Amy’s baby?', answers: ['Enigma', 'Elliot', 'Eleanor', 'Ella'] }
]
,

  himym: [
    { id: 'q1', text: 'What is the name of Ted\'s on-again, off-again girlfriend?', answers: ['Robin', 'Lily', 'Victoria', 'Stella'] },
    { id: 'q2', text: 'What instrument does Ted steal for Robin?', answers: ['Blue French horn', 'Red trumpet', 'Yellow tuba', 'Green saxophone'] },
    { id: 'q3', text: 'Which character is known for saying, "Legendary!"?', answers: ['Barney', 'Ted', 'Marshall', 'Robin'] },
    { id: 'q4', text: 'What is the name of the bar where the group often hangs out?', answers: ['MacLaren\'s', 'Puzzles', 'Central Pub', 'The Drunken Clam'] },
    { id: 'q5', text: 'Who was Ted\'s best man at his wedding to Stella?', answers: ['Marshall', 'Barney', 'Robin', 'Lily'] },
    { id: 'q6', text: 'What is the name of Lily and Marshall’s son?', answers: ['Marvin', 'James', 'Lucas', 'Henry'] },
    { id: 'q7', text: 'What job does Barney have?', answers: ['Please', 'Banker', 'Lawyer', 'Architect'] },
    { id: 'q8', text: 'What is the name of Ted\'s college girlfriend?', answers: ['Karen', 'Trudy', 'Victoria', 'Jeanette'] },
    { id: 'q9', text: 'What fruit does Ted wake up to after a drunken night out?', answers: ['Pineapple', 'Apple', 'Banana', 'Orange'] },
    { id: 'q10', text: 'Which character is Canadian?', answers: ['Robin', 'Barney', 'Lily', 'Ted'] },
    { id: 'q11', text: 'What is the name of the high school where Ted and Barney first met?', answers: ['Harrison High', 'Haverford High', 'Lincoln High', 'Westfield High'] },
    { id: 'q12', text: 'What is the name of Barney’s alter ego that he uses to pick up women?', answers: ['The Stinson', 'The Bro', 'The Suit', 'The Wingman'] },
    { id: 'q13', text: 'What does Ted call the group’s Sunday brunch?', answers: ['Brunch Club', 'The Sunday Funday', 'The Brunch Bunch', 'The Weekend Feast'] },
    { id: 'q14', text: 'Which city does Robin move to for her job in the later seasons?', answers: ['Tokyo', 'New York', 'Chicago', 'Toronto'] },
    { id: 'q15', text: 'What is the name of the bar where Ted and his friends often meet?', answers: ['MacLaren’s Pub', 'The Pub', 'The Bar', 'The Tavern'] },
    { id: 'q16', text: 'What is the name of Marshall’s law firm?', answers: ['Norseman Law Firm', 'Parker & Parker', 'Harrison & Harrison', 'Herman & Johnson'] },
    { id: 'q17', text: 'What does Barney often say to assert his confidence?', answers: ['“Suit up!”', '“Legendary!”', '“Challenge accepted!”', '“That’s awesome!”'] },
    { id: 'q18', text: 'What does Ted call the building where he lives?', answers: ['The Airstream', 'The Arcadia', 'The Montauk', 'The Central'] },
    { id: 'q19', text: 'What is the name of the play that Barney stars in during the show?', answers: ['The Playbook', 'The Bro Code', 'The Lotus', 'The Play'] },
    { id: 'q20', text: 'What is the name of the girl who steals Ted’s heart in the series finale?', answers: ['Tracy McConnell', 'Victoria', 'Stella', 'Robin'] }
  ],


  theOffice: [
    { id: 'q1', text: 'What is the name of the paper company where the show is set?', answers: ['Dunder Mifflin', 'Utica Paper', 'Staples', 'Office Depot'] },
    { id: 'q2', text: 'Who is the Regional Manager of the Scranton branch?', answers: ['Michael Scott', 'Dwight Schrute', 'Jim Halpert', 'Ryan Howard'] },
    { id: 'q3', text: 'What is the name of Michael Scott’s movie?', answers: ['Threat Level Midnight', 'The Office Movie', 'The Scranton Strangler', 'Jim & Pam'] },
    { id: 'q4', text: 'Which character has a beet farm?', answers: ['Dwight Schrute', 'Jim Halpert', 'Andy Bernard', 'Stanley Hudson'] },
    { id: 'q5', text: 'Who is Pam’s husband?', answers: ['Jim Halpert', 'Dwight Schrute', 'Ryan Howard', 'Michael Scott'] },
    { id: 'q6', text: 'What is the name of the receptionist at the Scranton branch?', answers: ['Pam Beesly', 'Angela Martin', 'Kelly Kapoor', 'Toby Flenderson'] },
    { id: 'q7', text: 'Who becomes the new Regional Manager at the end of the series?', answers: ['Jim Halpert', 'Dwight Schrute', 'Michael Scott', 'Andy Bernard'] },
    { id: 'q8', text: 'What is the name of the show within the show?', answers: ['The Office', 'Dunder Mifflin', 'Jim & Pam', 'Threat Level Midnight'] },
    { id: 'q9', text: 'What does Dwight call his office at his farm?', answers: ['The Beet Farm', 'The Schrute Estate', 'The Dark Lord’s Lair', 'The Office'] },
    { id: 'q10', text: 'What is Michael Scott’s favorite song?', answers: ['“That’s What She Said”', '“Take Me Home, Country Roads”', '“The Little Drummer Boy”', '“The First Noel”'] },
    { id: 'q11', text: 'What is Dwight’s nickname for his beet farm?', answers: ['Schrute Farms', 'The Beet Barn', 'The Farm', 'Dwight’s Estate'] },
    { id: 'q12', text: 'What is Michael Scott’s nickname for his office space?', answers: ['The Michael Scott Paper Company', 'The Scott Cave', 'The Bunker', 'The Office'] },
    { id: 'q13', text: 'What is Jim’s favorite prank to play on Dwight?', answers: ['Putting his stapler in Jell-O', 'Sending him fake faxes', 'Hiding his desk', 'Stealing his bobblehead'] },
    { id: 'q14', text: 'What is the name of the receptionist who replaces Pam in the later seasons?', answers: ['Erin Hannon', 'Angela Martin', 'Kelly Kapoor', 'Jan Levinson'] },
    { id: 'q15', text: 'What is Pam’s profession before she becomes a saleswoman?', answers: ['Receptionist', 'Customer Service Representative', 'Graphic Designer', 'Office Manager'] },
    { id: 'q16', text: 'What is the name of the documentary crew’s producer?', answers: ['Greg Daniels', 'Elan Gold', 'Toby Flenderson', 'David Wallace'] },
    { id: 'q17', text: 'What is the name of Michael Scott’s “inspirational” seminar?', answers: ['Michael Scott’s Fun Time Seminar', 'The Scott Seminar', 'The Motivational Seminar', 'The Scott Way'] },
    { id: 'q18', text: 'What does Dwight keep in his “world’s best boss” mug?', answers: ['Pens', 'Cough drops', 'Candy', 'Mints'] },
    { id: 'q19', text: 'What does Andy Bernard use as his ringtone?', answers: ['“Take Me Home, Country Roads”', '“The Office Theme”', '“The Lonely Island”', '“Here Comes the Sun”'] },
    { id: 'q20', text: 'What is the name of Jim and Pam’s second child?', answers: ['Philip', 'Cecilia', 'Emily', 'Sophie'] },
  ],

  modernFamily: [
    { id: 'q1', text: 'What is the name of Jay’s dog?', answers: ['Stella', 'Bella', 'Lola', 'Daisy'] },
    { id: 'q2', text: 'Who did Mitchell marry?', answers: ['Cameron', 'Phil', 'Jay', 'Pepper'] },
    { id: 'q3', text: 'What is the name of Phil’s real estate business?', answers: ['Phil Dunphy Realty', 'Dunphy Realty Co.', 'California Homes', 'Dunphy Properties'] },
    { id: 'q4', text: 'Which character has a fear of clowns?', answers: ['Phil', 'Mitchell', 'Gloria', 'Manny'] },
    { id: 'q5', text: 'Who is Gloria’s ex-husband?', answers: ['Javier', 'Manny', 'Phil', 'Andy'] },
    { id: 'q6', text: 'What job does Claire take up after leaving the family business?', answers: ['Councilwoman', 'Interior Designer', 'CEO', 'Stay-at-home Mom'] },
    { id: 'q7', text: 'What is the name of Cam and Mitchell’s adopted daughter?', answers: ['Lily', 'Mia', 'Sofia', 'Emma'] },
    { id: 'q8', text: 'What is the age difference between Jay and Gloria?', answers: ['25 years', '10 years', '20 years', '15 years'] },
    { id: 'q9', text: 'Which character is known for their “cool dad” persona?', answers: ['Phil', 'Jay', 'Cameron', 'Mitchell'] },
    { id: 'q10', text: 'What sport did Gloria excel at in her youth?', answers: ['Shooting', 'Soccer', 'Tennis', 'Boxing'] },
    { id: 'q11', text: 'Who works as a professional clown?', answers: ['Cameron', 'Phil', 'Mitchell', 'Jay'] },
    { id: 'q12', text: 'What is Manny’s full name?', answers: ['Manuel Alberto Javier Alejandro Delgado', 'Manuel Alejandro Delgado-Pritchett', 'Manuel Ricardo Delgado Pritchett', 'Manuel Delgado Santiago'] },
    { id: 'q13', text: 'What was Haley’s first job?', answers: ['Fashion Assistant', 'Waitress', 'Receptionist', 'Real Estate Agent'] },
    { id: 'q14', text: 'Who does Luke take to prom in high school?', answers: ['Manny', 'Alex', 'Phil', 'Lily'] },
    { id: 'q15', text: 'What is the nickname Phil gives his alter ego?', answers: ['Clive Bixby', 'Ace Wilder', 'Clint Reardon', 'Rick Thrill'] },
    { id: 'q16', text: 'Which character is known for using motivational “Phil-osophies”?', answers: ['Phil', 'Jay', 'Cameron', 'Mitchell'] },
    { id: 'q17', text: 'What is the name of Jay’s closet company?', answers: ['Closets, Closets, Closets!', 'Pritchett’s Closets & Blinds', 'California Closets', 'Custom Closets'] },
    { id: 'q18', text: 'Where do Cam and Mitchell get married?', answers: ['At a vineyard', 'On the beach', 'In a courthouse', 'At Jay’s house'] },
    { id: 'q19', text: 'Which of the Dunphy kids is the oldest?', answers: ['Haley', 'Alex', 'Luke', 'Manny'] },
    { id: 'q20', text: 'What is the name of Phil’s nemesis in real estate?', answers: ['Gil Thorpe', 'Ronnie LaFontaine', 'Jerry Claw', 'Hank Cassidy'] },
  ],

  bigBangTheory: [
    { id: 'q1', text: 'What is Sheldon Cooper’s IQ?', answers: ['187', '180', '160', '200'] },
    { id: 'q2', text: 'What is Leonard Hofstadter’s profession?', answers: ['Experimental Physics', 'Engineering', 'Mathematics', 'Astronomy'] },
    { id: 'q3', text: 'What is the name of Sheldon’s girlfriend who becomes his wife?', answers: ['Amy Farrah Fowler', 'Penny', 'Bernadette Rostenkowski', 'Priya'] },
    { id: 'q4', text: 'What is the name of Penny’s ex-boyfriend who is also an actor?', answers: ['Beverly Hofstadter', 'Wil Wheaton', 'Rajesh Koothrappali', 'Howard Wolowitz'] },
    { id: 'q5', text: 'What is Howard Wolowitz’s profession?', answers: ['Engineer', 'Physicist', 'Astronomer', 'Chemist'] },
    { id: 'q6', text: 'Which character is known for their inability to get a date in the earlier seasons?', answers: ['Rajesh Koothrappali', 'Sheldon Cooper', 'Leonard Hofstadter', 'Howard Wolowitz'] },
    { id: 'q7', text: 'What is the name of Sheldon’s favorite comic book store?', answers: ['The Comic Center of Pasadena', 'The Nerd Emporium', 'The Geek Hut', 'The Comic Cave'] },
    { id: 'q8', text: 'What is the name of the group of friends in the show?', answers: ['The Big Bang Theory', 'The Nerd Herd', 'The Geek Squad', 'The Brain Trust'] },
    { id: 'q9', text: 'What is Penny’s last name?', answers: ['Hofstadter', 'Harrison', 'Wheaton', 'Rostenkowski'] },
    { id: 'q10', text: 'What is Rajesh’s pet name for his dog?', answers: ['Cinnamon', 'Peanut', 'Buddy', 'Max'] },
    { id: 'q11', text: 'What is the name of the group’s favorite comic book store?', answers: ['The Comic Center of Pasadena', 'The Nerd Emporium', 'The Geek Spot', 'The Comic Book Cave'] },
    { id: 'q12', text: 'What is Leonard’s apartment number?', answers: ['4A', '4B', '5A', '5B'] },
    { id: 'q13', text: 'What does Sheldon believe is his “personal flag”?', answers: ['A flag with his face on it', 'The flag of the United Nations', 'The American flag', 'A flag with a superhero emblem'] },
    { id: 'q14', text: 'What is Howard’s mother’s name?', answers: ['Mrs. Wolowitz', 'Esther Wolowitz', 'Miriam Wolowitz', 'Rita Wolowitz'] },
    { id: 'q15', text: 'What is Penny’s job in the earlier seasons?', answers: ['Waitress', 'Sales Representative', 'Nurse', 'Barista'] },
    { id: 'q16', text: 'What does Sheldon call his spot on the couch?', answers: ['His spot', 'The Sheldon Spot', 'The Comfort Zone', 'The Prime Location'] },
    { id: 'q17', text: 'What is the name of the group’s favorite TV show?', answers: ['Star Wars', 'Star Trek', 'Doctor Who', 'Battlestar Galactica'] },
    { id: 'q18', text: 'What is Rajesh’s job at the university?', answers: ['Astrophysicist', 'Biochemist', 'Geneticist', 'Computer Scientist'] },
    { id: 'q19', text: 'What is the name of Sheldon’s roommate agreement?', answers: ['The Roommate Agreement', 'The Living Agreement', 'The Apartment Rules', 'The Shared Space Agreement'] },
    { id: 'q20', text: 'What is Leonard’s favorite hobby?', answers: ['Playing video games', 'Reading comics', 'Collecting action figures', 'Playing board games'] }
  ]
};

export default questions;
